### PR TITLE
In Case You're Interested

### PR DESCRIPTION
**Pull request by jspizziri**
Hey, first thanks for all the work on this.

Just wanted to let you know that we've forked the project and have been making some changes. Thought I'd create a PR and let you look at what we've done and if you're interested in any of the commits/functionality we can try and get some mergeable MR's sent your way.

### CODE REVIEW

**Comment by igneus** [comment]
Hi, thanks, I'm aware of your fork and I follow it with curiosity. (It's the only instance ever of my software being forked and developed further, so a bit of excitement is understandable.)

I am particularly interested in your [changes of English feast names](https://github.com/Lumen-de-Lumine/calendarium-romanum/commit/b9c3e8b89c95327030f9aa82429ce40e7bd8a962). What's their point of reference? Do they follow calendar printed in some official liturgical book (which one?), or in some other official resource?
If your corrections result from proofreading against, say, calendar of the current US missal, I would love to merge them.

On the other hand, the recently added vigils are an example of a functionality which I would never integrate in the mainline calendarium-romanum, since the gem's scope is limited to computing liturgical calendar in a narrow sense (the few book-specific features implemented early, when the gem's scope was not yet clearly defined, will be removed in 1.0) and vigils are a feature limited to the missal and lectionary.

**Comment by jspizziri** [comment]
@bbloomf, I believe the name updates came from the USCCB's Missal, correct?

Additionally, we've been making some changes to the API wrapper as well, some of the things we've implemented are a Docker implmentation (which I know you merged in recently); however, you might want to look at ours, as we've found passenger far more performant than puma (in our other ruby/rails projects). Additionally, we've implemented some functionality that allows for some basic querying of celebrations which might be useful.

We're also pushing a public docker image to Docker hub when we cut new releases:

https://hub.docker.com/r/sourceandsummit/church-calendar-api

**Comment by bbloomf** [comment]
Yes, the name updates come from the 2011 US edition of the Roman Missal.

**Comment by igneus** [comment]
Then, if you offer "mergeable MR's sent my way", I would love to have one with b9c3e8b89c95327030f9aa82429ce40e7bd8a962 , but just the changes to `data/universal-en.txt` without adding the US calendar. (It's definitely a valuable piece of calendar data, but at this point of time I don't want to include in the mainline calendarium-romanum data which I wouldn't be able to verify and keep up-to-date.)

**Pull request closed without merging**
