### PR TITLE
creates day.weekday_name for human-readable weekday

### PR DESCRIPTION
**Pull request by RonWalker22**

### CODE REVIEW

**Comment by igneus** [comment]
Hi, thank you very much! This is an almost perfect implementation of #34 , the only missing bit is internationalization. Would you add it? The weekday names in all currently supported languages are already prepared (see `config/locales`).

**Comment by RonWalker22** [comment]
Ok. I will add it.

**Comment by RonWalker22** [comment]
I will review the failed test and update accordingly

**Comment by igneus** [comment]
Everything fixed before I could finish the review :smile:  :+1: Thank you very much. Merging.

Closes #34

**Pull request merged**
