### PR TITLE
Instructions to install and use calendarium-romanum as a standalone Linux terminal application

### PR DESCRIPTION
**Pull request by historical-theology**

### CODE REVIEW

**Comment by igneus** [comment]
Hi, thanks for the effort put into this contribution! Documentation improvements are definitely welcome. I am, however, not going to merge this PR:

* `calendarium-romanum` is a Ruby gem and is to be installed as such (either `gem install ...` or specify it as a dependency in a project using Bundler). The way of manual installation you suggest is hacky and I definitely don't encourage anyone to use it.
* `Copy the whole folder "calendarium-romanum" (lib/calendarium-romanum) directly into the root "lib" folder on your system (/lib) ... Copy the file "calendariumrom" (bin/calendariumrom) directly into "usr/bin" on your system.` -- this wouldn't even work, since `/lib` is usually not on the Ruby library path list
* the `calendariumrom` executable currently contains mostly development tools and has rather little value for an end user; I don't advertise it much, since it's planned to extract the calendar querying functionality (currently in the subcommand `calendariumrom query`) to a separate Ruby gem, depending on `calendarium-romanum`, and make it more user-friendly and useful

Thank you for your understanding.

**Comment by historical-theology** [comment]
@igneus , thank you for the thoughtful reply. I certainly understand your reasoning, but I should add a follow up note that the method that I have outlined _does_ work -- at least for me (?). I have tested it both in Manjaro XFCE Minimal and Manjaro Gnome (full).

**Comment by historical-theology** [comment]
Strangely enough, it did in fact work flawlessly for me in Manjaro XFCE but not the Gnome DE. I need to reevaluate the matter, clearly. Thank you.

**Comment by historical-theology** [comment]
To follow up, I see what happened now. I grabbed the gem first. I need to rewrite that blog post, it would seem...

**Pull request closed without merging**
